#!/bin/sh

iface=$1
cmd=$2
# скрипт отвечает только за фоновый запуск логики Wifi
# необходим для того, чтобы udev не прерывал скрипт по своему таймауту (30 сек)
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/etc/network/wlan-up "$iface" "$cmd" &
